export const EDITOR_STATE = {
  COMPOSING: "COMPOSING",
  MOUNTED: "MOUNTED",
  READONLY: "READONLY",
  MOUSE_DOWN: "MOUSE_DOWN",
  FOCUS: "FOCUS",
} as const;

export const APPLY_SOURCE = {
  USER: "USER",
  HISTORY: "HISTORY",
};
